# SPDX-License-Identifier: Apache-2.0
#
# http://nexb.com and https://github.com/aboutcode-org/scancode.io
# The ScanCode.io software is licensed under the Apache License version 2.0.
# Data generated with ScanCode.io is provided as-is without warranties.
# ScanCode is a trademark of nexB Inc.
#
# You may not use this software except in compliance with the License.
# You may obtain a copy of the License at: http://apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
# Data Generated with ScanCode.io is provided on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied. No content created from
# ScanCode.io should be considered or used as legal advice. Consult an Attorney
# for any legal advice.
#
# ScanCode.io is a free software code scanning tool from nexB Inc. and others.
# Visit https://github.com/aboutcode-org/scancode.io for support and download.

from pathlib import Path
from unittest import TestCase
from unittest.mock import Mock, patch

from scanpipe.models import CodebaseResource
from scanpipe.models import DiscoveredPackage
from scanpipe.models import Project
from scanpipe.pipes import maven


class ScanPipeMavenTest(TestCase):
    def setUp(self):
        self.project = Project.objects.create(name="Test Maven Project")
        
    def tearDown(self):
        self.project.delete()

    def test_detect_maven_jars_from_pom_properties_basic(self):
        """Test basic Maven JAR detection from pom.properties files."""
        # Create test files in the project's codebase directory
        test_jar_extract_dir = self.project.codebase_path / "test.jar-extract" / "META-INF" / "maven" / "io.perfmark" / "perfmark-api"
        test_jar_extract_dir.mkdir(parents=True)
        
        pom_properties_path = test_jar_extract_dir / "pom.properties"
        pom_properties_content = (
            "# Generated by Maven\n"
            "groupId=io.perfmark\n"
            "artifactId=perfmark-api\n"
            "version=0.27.0\n"
        )
        pom_properties_path.write_text(pom_properties_content)
        
        # Create CodebaseResource without setting location (it's computed)
        pom_resource = CodebaseResource.objects.create(
            project=self.project,
            path="test.jar-extract/META-INF/maven/io.perfmark/perfmark-api/pom.properties",
            name="pom.properties",
            type=CodebaseResource.Type.FILE
        )
        
        # Create a JAR package (incorrectly detected as jar type)
        jar_package = DiscoveredPackage.objects.create(
            project=self.project,
            type="jar",
            name="perfmark-api",
            version="0.27.0"
        )
        
        # Run the Maven detection
        result = maven.detect_maven_jars_from_pom_properties(self.project)
        
        # Verify results
        self.assertEqual(1, result)
        
        # Refresh the package from database
        jar_package.refresh_from_db()
        
        # Check that the package was updated to Maven type
        self.assertEqual("maven", jar_package.type)
        self.assertEqual("io.perfmark", jar_package.namespace)
        self.assertEqual("perfmark-api", jar_package.name)
        self.assertEqual("0.27.0", jar_package.version)

    @patch('pathlib.Path.read_text')
    def test_extract_maven_coordinates_from_pom_properties(self, mock_read_text):
        """Test extraction of Maven coordinates from pom.properties content."""
        # Mock the file content
        mock_read_text.return_value = (
            "# Generated by Maven\n"
            "# Some comment\n"
            "groupId=io.perfmark\n"
            "artifactId=perfmark-api\n"
            "version=0.27.0\n"
            "someOtherProperty=value\n"
        )
        
        # Create a mock CodebaseResource
        mock_resource = Mock()
        mock_resource.location = "/fake/path/pom.properties"
        
        # Mock Path.exists to return True
        with patch('pathlib.Path.exists', return_value=True):
            # Test the extraction function
            coords = maven.get_maven_coordinates_from_pom_properties(mock_resource)
            
            # Verify the extracted coordinates
            expected = {
                'group_id': 'io.perfmark',
                'artifact_id': 'perfmark-api',
                'version': '0.27.0'
            }
            self.assertEqual(expected, coords)

    @patch('pathlib.Path.read_text')
    def test_extract_maven_coordinates_missing_fields(self, mock_read_text):
        """Test extraction when required fields are missing."""
        # Mock the file content with missing fields
        mock_read_text.return_value = (
            "# Generated by Maven\n"
            "groupId=io.perfmark\n"
            "# artifactId is missing\n"
            "version=0.27.0\n"
        )
        
        # Create a mock CodebaseResource
        mock_resource = Mock()
        mock_resource.location = "/fake/path/pom.properties"
        
        # Mock Path.exists to return True
        with patch('pathlib.Path.exists', return_value=True):
            # Test the extraction function
            coords = maven.get_maven_coordinates_from_pom_properties(mock_resource)
            
            # Should return None when required fields are missing
            self.assertIsNone(coords)

    def test_no_maven_jars_detected(self):
        """Test that no changes are made when no Maven JARs are found."""
        # Create a regular JAR package without Maven metadata
        jar_package = DiscoveredPackage.objects.create(
            project=self.project,
            type="jar",
            name="some-library",
            version="1.0.0",
            package_uid="pkg:jar/some-library@1.0.0"
        )
        
        # Run the Maven detection
        result = maven.detect_maven_jars_from_pom_properties(self.project)
        
        # Verify no packages were modified
        self.assertEqual(0, result)
        
        # Refresh the package from database
        jar_package.refresh_from_db()
        
        # Check that the package remains unchanged
        self.assertEqual("jar", jar_package.type)
        self.assertEqual("some-library", jar_package.name)
        self.assertEqual("1.0.0", jar_package.version)