# SPDX-License-Identifier: Apache-2.0
#
# http://nexb.com and https://github.com/nexB/scancode.io
# The ScanCode.io software is licensed under the Apache License version 2.0.
# Data generated with ScanCode.io is provided as-is without warranties.
# ScanCode is a trademark of nexB Inc.
#
# You may not use this software except in compliance with the License.
# You may obtain a copy of the License at: http://apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
# Data Generated with ScanCode.io is provided on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied. No content created from
# ScanCode.io should be considered or used as legal advice. Consult an Attorney
# for any legal advice.
#
# ScanCode.io is a free software code scanning tool from nexB Inc. and others.
# Visit https://github.com/nexB/scancode.io for support and download.

"""
Test suite for validating ScanCode.io integrations with third-party SCA SBOM tools.

Each test ensures that SBOM files generated by tools such as Anchore Grype,
CycloneDX (cdxgen), osv-scanner, Trivy, SBOM Tool, and more.

Adding new test data
====================

1. Generate an SBOM with the tool you want to test. For example with Trivy:

    trivy image --scanners vuln,license --format cyclonedx \
        --output trivy-alpine-3.17-sbom.json alpine:3.17.0

2. Save the SBOM file under:
    tests/data/integrations-sca/

3. Add expected counts for that SBOM to `TEST_DATA`` below.

Example:
    "trivy-alpine-3.17-sbom.json": {
        "resources": 1,
        "packages": 16,
        "vulnerable_packages": 7,
        "dependencies": 25,
        "vulnerabilities": 10,
        "purls": [
            "pkg:unknown/alpine@3.17.0",
        ],
    },

   Tip: run the test once without expected values, check the counts from the
   failure messages, then update the dictionary accordingly.

4. Run the test suite:

    ./manage.py test scanpipe.tests.test_integrations_sca

5. Commit both the SBOM file and dictionary entry.

"""

from pathlib import Path

from django.test import TestCase

from scanpipe.pipes import benchmark
from scanpipe.tests import make_project

# Mapping of SBOM filenames to expected counts.
# Each SBOM is stored under ``tests/data/sca-integrations/``.
# Keys are filenames, values are dicts with expected numbers of:
# - ``resources``: CodebaseResource
# - ``packages``: DiscoveredPackages
# - ``vulnerable_packages``: Vulnerable DiscoveredPackages
# - ``dependencies``: DiscoveredDependencies
# - ``vulnerabilities``: Expected number of unique vulnerabilities.
# - ``purls``: The list of PURLs present in the SBOM
TEST_DATA = {
    ### Anchore Grype
    #   $ grype -v -o cyclonedx-json \
    #       --file anchore-alpine-3.17-sbom.json alpine:3.17.0
    "anchore-alpine-3.17-sbom.json": {
        "resources": 1,
        "packages": 94,
        "vulnerable_packages": 7,
        "dependencies": 20,
        "vulnerabilities": 37,
        "purls": [
            "pkg:apk/alpine/alpine-baselayout-data@3.4.0-r0?arch=x86_64&distro=alpine-3.17.0&upstream=alpine-baselayout",
            "pkg:apk/alpine/alpine-baselayout@3.4.0-r0?arch=x86_64&distro=alpine-3.17.0",
            "pkg:apk/alpine/alpine-keys@2.4-r1?arch=x86_64&distro=alpine-3.17.0",
            "pkg:apk/alpine/apk-tools@2.12.10-r1?arch=x86_64&distro=alpine-3.17.0",
            "pkg:apk/alpine/busybox-binsh@1.35.0-r29?arch=x86_64&distro=alpine-3.17.0&upstream=busybox",
            "pkg:apk/alpine/busybox@1.35.0-r29?arch=x86_64&distro=alpine-3.17.0",
            "pkg:apk/alpine/ca-certificates-bundle@20220614-r2?arch=x86_64&distro=alpine-3.17.0&upstream=ca-certificates",
            "pkg:apk/alpine/libc-utils@0.7.2-r3?arch=x86_64&distro=alpine-3.17.0&upstream=libc-dev",
            "pkg:apk/alpine/libcrypto3@3.0.7-r0?arch=x86_64&distro=alpine-3.17.0&upstream=openssl",
            "pkg:apk/alpine/libssl3@3.0.7-r0?arch=x86_64&distro=alpine-3.17.0&upstream=openssl",
            "pkg:apk/alpine/musl-utils@1.2.3-r4?arch=x86_64&distro=alpine-3.17.0&upstream=musl",
            "pkg:apk/alpine/musl@1.2.3-r4?arch=x86_64&distro=alpine-3.17.0",
            "pkg:apk/alpine/scanelf@1.3.5-r1?arch=x86_64&distro=alpine-3.17.0&upstream=pax-utils",
            "pkg:apk/alpine/ssl_client@1.35.0-r29?arch=x86_64&distro=alpine-3.17.0&upstream=busybox",
            "pkg:apk/alpine/zlib@1.2.13-r0?arch=x86_64&distro=alpine-3.17.0",
            "pkg:unknown/alpine@3.17.0",
            "pkg:unknown/bin/busybox",
            "pkg:unknown/etc/apk/keys/alpine-devel%40lists.alpinelinux.org-4a6a0840.rsa.pub",
            "pkg:unknown/etc/apk/keys/alpine-devel%40lists.alpinelinux.org-5243ef4b.rsa.pub",
            "pkg:unknown/etc/apk/keys/alpine-devel%40lists.alpinelinux.org-5261cecb.rsa.pub",
            "pkg:unknown/etc/apk/keys/alpine-devel%40lists.alpinelinux.org-6165ee59.rsa.pub",
            "pkg:unknown/etc/apk/keys/alpine-devel%40lists.alpinelinux.org-61666e3f.rsa.pub",
            "pkg:unknown/etc/crontabs/root",
            "pkg:unknown/etc/fstab",
            "pkg:unknown/etc/group",
            "pkg:unknown/etc/hostname",
            "pkg:unknown/etc/hosts",
            "pkg:unknown/etc/inittab",
            "pkg:unknown/etc/logrotate.d/acpid",
            "pkg:unknown/etc/modprobe.d/aliases.conf",
            "pkg:unknown/etc/modprobe.d/blacklist.conf",
            "pkg:unknown/etc/modprobe.d/i386.conf",
            "pkg:unknown/etc/modprobe.d/kms.conf",
            "pkg:unknown/etc/modules",
            "pkg:unknown/etc/motd",
            "pkg:unknown/etc/network/if-up.d/dad",
            "pkg:unknown/etc/nsswitch.conf",
            "pkg:unknown/etc/passwd",
            "pkg:unknown/etc/profile",
            "pkg:unknown/etc/profile.d/README",
            "pkg:unknown/etc/profile.d/color_prompt.sh.disabled",
            "pkg:unknown/etc/profile.d/locale.sh",
            "pkg:unknown/etc/protocols",
            "pkg:unknown/etc/securetty",
            "pkg:unknown/etc/services",
            "pkg:unknown/etc/shadow",
            "pkg:unknown/etc/shells",
            "pkg:unknown/etc/ssl/certs/ca-certificates.crt",
            "pkg:unknown/etc/ssl/ct_log_list.cnf",
            "pkg:unknown/etc/ssl/ct_log_list.cnf.dist",
            "pkg:unknown/etc/ssl/misc/CA.pl",
            "pkg:unknown/etc/ssl/misc/tsget.pl",
            "pkg:unknown/etc/ssl/openssl.cnf",
            "pkg:unknown/etc/ssl/openssl.cnf.dist",
            "pkg:unknown/etc/sysctl.conf",
            "pkg:unknown/etc/udhcpd.conf",
            "pkg:unknown/lib/apk/db/installed",
            "pkg:unknown/lib/ld-musl-x86_64.so.1",
            "pkg:unknown/lib/libapk.so.3.12.0",
            "pkg:unknown/lib/libcrypto.so.3",
            "pkg:unknown/lib/libssl.so.3",
            "pkg:unknown/lib/libz.so.1.2.13",
            "pkg:unknown/lib/sysctl.d/00-alpine.conf",
            "pkg:unknown/sbin/apk",
            "pkg:unknown/sbin/ldconfig",
            "pkg:unknown/usr/bin/getconf",
            "pkg:unknown/usr/bin/getent",
            "pkg:unknown/usr/bin/iconv",
            "pkg:unknown/usr/bin/ldd",
            "pkg:unknown/usr/bin/scanelf",
            "pkg:unknown/usr/bin/ssl_client",
            "pkg:unknown/usr/lib/engines-3/afalg.so",
            "pkg:unknown/usr/lib/engines-3/capi.so",
            "pkg:unknown/usr/lib/engines-3/loader_attic.so",
            "pkg:unknown/usr/lib/engines-3/padlock.so",
            "pkg:unknown/usr/lib/ossl-modules/legacy.so",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-4a6a0840.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-5243ef4b.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-524d27bb.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-5261cecb.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-58199dcc.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-58cbb476.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-58e4f17d.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-5e69ca50.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-60ac2099.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-6165ee59.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-61666e3f.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-616a9724.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-616abc23.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-616ac3bc.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-616adfeb.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-616ae350.rsa.pub",
            "pkg:unknown/usr/share/apk/keys/alpine-devel%40lists.alpinelinux.org-616db30d.rsa.pub",
            "pkg:unknown/usr/share/udhcpc/default.script",
        ],
    },
    ### CycloneDX cdxgen
    #   $ cdxgen alpine:3.17.0 --type docker --spec-version 1.6 --json-pretty \
    #       --output cdxgen-alpine-3.17-sbom.json
    "cdxgen-alpine-3.17-sbom.json": {
        "resources": 1,
        "packages": 14,
        "vulnerable_packages": 0,
        "dependencies": 0,
        "vulnerabilities": 0,
        "purls": [
            "pkg:generic/apk",
            "pkg:generic/busybox",
            "pkg:generic/getconf",
            "pkg:generic/getent",
            "pkg:generic/iconv",
            "pkg:generic/ld-musl-x86_64.so.1",
            "pkg:generic/ldconfig",
            "pkg:generic/ldd",
            "pkg:generic/libapk.so.3.12.0",
            "pkg:generic/libcrypto.so.3",
            "pkg:generic/libssl.so.3",
            "pkg:generic/libz.so.1.2.13",
            "pkg:generic/scanelf",
            "pkg:generic/ssl_client",
        ],
    },
    ### OWASP dep-scan
    #   $ depscan --src alpine:3.17.0 --type docker
    "depscan-alpine-3.17-sbom.json": {
        "resources": 1,
        "packages": 33,
        "vulnerable_packages": 3,
        "dependencies": 20,
        "vulnerabilities": 35,
        "purls": [
            "pkg:apk/alpine/alpine-baselayout-data@3.4.0-r0?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/alpine-baselayout@3.4.0-r0?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/alpine-keys@2.4-r1?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/apk-tools@2.12.10-r1?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/busybox-binsh@1.35.0-r29?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/busybox@1.35.0-r29?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/ca-certificates-bundle@20220614-r2?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/ca-certificates@20220614-r2?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/libc-dev@0.7.2-r3?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/libc-utils@0.7.2-r3?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/libcrypto3@3.0.7-r0?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/libssl3@3.0.7-r0?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/musl-utils@1.2.3-r4?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/musl@1.2.3-r4?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/openssl@3.0.7-r0?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/pax-utils@1.3.5-r1?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/scanelf@1.3.5-r1?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/ssl_client@1.35.0-r29?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:apk/alpine/zlib@1.2.13-r0?arch=x86_64&distro=alpine-3.17.0&distro_name=alpine-3.17",
            "pkg:generic/apk",
            "pkg:generic/busybox",
            "pkg:generic/getconf",
            "pkg:generic/getent",
            "pkg:generic/iconv",
            "pkg:generic/ld-musl-x86_64.so.1",
            "pkg:generic/ldconfig",
            "pkg:generic/ldd",
            "pkg:generic/libapk.so.3.12.0",
            "pkg:generic/libcrypto.so.3",
            "pkg:generic/libssl.so.3",
            "pkg:generic/libz.so.1.2.13",
            "pkg:generic/scanelf",
            "pkg:generic/ssl_client",
        ],
    },
    ### OSV-Scanner
    #   $ osv-scanner scan image alpine:3.17.0 \
    #       --all-packages \
    #       --format spdx-2-3 \
    #       --output osv-scanner-alpine-3.17-sbom.spdx.json
    "osv-scanner-alpine-3.17-sbom.spdx.json": {
        "resources": 1,
        "packages": 16,
        "vulnerable_packages": 0,
        "dependencies": 15,
        "vulnerabilities": 0,
        "purls": [
            "pkg:apk/alpine/alpine-baselayout-data@3.4.0-r0?arch=x86_64&distro=3.17.0&origin=alpine-baselayout",
            "pkg:apk/alpine/alpine-baselayout@3.4.0-r0?arch=x86_64&distro=3.17.0&origin=alpine-baselayout",
            "pkg:apk/alpine/alpine-keys@2.4-r1?arch=x86_64&distro=3.17.0&origin=alpine-keys",
            "pkg:apk/alpine/apk-tools@2.12.10-r1?arch=x86_64&distro=3.17.0&origin=apk-tools",
            "pkg:apk/alpine/busybox-binsh@1.35.0-r29?arch=x86_64&distro=3.17.0&origin=busybox",
            "pkg:apk/alpine/busybox@1.35.0-r29?arch=x86_64&distro=3.17.0&origin=busybox",
            "pkg:apk/alpine/ca-certificates-bundle@20220614-r2?arch=x86_64&distro=3.17.0&origin=ca-certificates",
            "pkg:apk/alpine/libc-utils@0.7.2-r3?arch=x86_64&distro=3.17.0&origin=libc-dev",
            "pkg:apk/alpine/libcrypto3@3.0.7-r0?arch=x86_64&distro=3.17.0&origin=openssl",
            "pkg:apk/alpine/libssl3@3.0.7-r0?arch=x86_64&distro=3.17.0&origin=openssl",
            "pkg:apk/alpine/musl-utils@1.2.3-r4?arch=x86_64&distro=3.17.0&origin=musl",
            "pkg:apk/alpine/musl@1.2.3-r4?arch=x86_64&distro=3.17.0&origin=musl",
            "pkg:apk/alpine/scanelf@1.3.5-r1?arch=x86_64&distro=3.17.0&origin=pax-utils",
            "pkg:apk/alpine/ssl_client@1.35.0-r29?arch=x86_64&distro=3.17.0&origin=busybox",
            "pkg:apk/alpine/zlib@1.2.13-r0?arch=x86_64&distro=3.17.0&origin=zlib",
            "pkg:unknown/main@0",
        ],
    },
    # Example file from osv-scanner documentation:
    # https://google.github.io/osv-scanner/output/#cyclonedx
    "osv-scanner-vulns-sbom.cdx.json": {
        "resources": 1,
        "packages": 3,
        "vulnerable_packages": 1,
        "dependencies": 0,
        "vulnerabilities": 1,
        "purls": [
            "pkg:composer/league/flysystem@1.0.8",
            "pkg:npm/has-flag@4.0.0",
            "pkg:npm/wrappy@1.0.2",
        ],
    },
    ### SBOM Tool
    #   $ sbom-tool generate -di alpine:3.17.0 \
    #       -pn DockerImage -pv 1.0.0 -ps Company -nsb https://sbom.company.com
    "sbom-tool-alpine-3.17-sbom.spdx.json": {
        "resources": 1,
        "packages": 16,
        "vulnerable_packages": 0,
        "dependencies": 15,
        "vulnerabilities": 0,
        "purls": [
            "pkg:swid/Company/sbom.company.com/DockerImage@1.0.0?tag_id=60e3f440-f9a8-449e-b516-da3049700fff",
            "pkg:unknown/alpine-baselayout-data@3.4.0-r0",
            "pkg:unknown/alpine-baselayout@3.4.0-r0",
            "pkg:unknown/alpine-keys@2.4-r1",
            "pkg:unknown/apk-tools@2.12.10-r1",
            "pkg:unknown/busybox-binsh@1.35.0-r29",
            "pkg:unknown/busybox@1.35.0-r29",
            "pkg:unknown/ca-certificates-bundle@20220614-r2",
            "pkg:unknown/libc-utils@0.7.2-r3",
            "pkg:unknown/libcrypto3@3.0.7-r0",
            "pkg:unknown/libssl3@3.0.7-r0",
            "pkg:unknown/musl-utils@1.2.3-r4",
            "pkg:unknown/musl@1.2.3-r4",
            "pkg:unknown/scanelf@1.3.5-r1",
            "pkg:unknown/ssl_client@1.35.0-r29",
            "pkg:unknown/zlib@1.2.13-r0",
        ],
    },
    ### Trivy
    #   $ trivy image --scanners vuln,license --format cyclonedx \
    #       --output trivy-alpine-3.17-sbom.json alpine:3.17.0
    "trivy-alpine-3.17-sbom.json": {
        "resources": 1,
        "packages": 16,
        "vulnerable_packages": 7,
        "dependencies": 25,
        "vulnerabilities": 33,
        "purls": [
            "pkg:apk/alpine/alpine-baselayout-data@3.4.0-r0?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/alpine-baselayout@3.4.0-r0?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/alpine-keys@2.4-r1?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/apk-tools@2.12.10-r1?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/busybox-binsh@1.35.0-r29?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/busybox@1.35.0-r29?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/ca-certificates-bundle@20220614-r2?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/libc-utils@0.7.2-r3?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/libcrypto3@3.0.7-r0?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/libssl3@3.0.7-r0?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/musl-utils@1.2.3-r4?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/musl@1.2.3-r4?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/scanelf@1.3.5-r1?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/ssl_client@1.35.0-r29?arch=x86_64&distro=3.17.0",
            "pkg:apk/alpine/zlib@1.2.13-r0?arch=x86_64&distro=3.17.0",
            "pkg:unknown/alpine@3.17.0",
        ],
    },
}


class ScanPipeIntegrationsBaseTest(TestCase):
    """
    Run consistency checks across all SBOM integration test files.

    For each SBOM listed in ``TEST_DATA``, this test:
    - Loads the SBOM into a temporary ScanCode.io project.
    - Executes the ``load_sbom`` pipeline.
    - Verifies that the number of resources, packages, vulnerable packages,
      and dependencies match the expected values.
    """

    data = None

    def _test_scanpipe_sca_integrations_tool(self, sbom_filename, expected_results):
        """Run a single SBOM integration test."""
        input_location = self.data / sbom_filename

        # Create a fresh project and load the SBOM into it
        project = make_project()
        project.copy_input_from(input_location)

        run = project.add_pipeline(pipeline_name="load_sbom")
        pipeline = run.make_pipeline_instance()

        exitcode, out = pipeline.execute()
        # Ensure the SBOM is properly loaded
        self.assertEqual(0, exitcode, msg=out)

        # Verify resource, package, vulnerability, and dependency counts
        self.assertEqual(
            expected_results["resources"],
            project.codebaseresources.count(),
            msg=f"[resources] {sbom_filename}",
        )
        self.assertEqual(
            expected_results["packages"],
            project.discoveredpackages.count(),
            msg=f"[packages] {sbom_filename}",
        )
        self.assertEqual(
            expected_results["dependencies"],
            project.discovereddependencies.count(),
            msg=f"[dependencies] {sbom_filename}",
        )

        vulnerable_packages = expected_results.get("vulnerable_packages")
        if vulnerable_packages:
            self.assertEqual(
                vulnerable_packages,
                project.discoveredpackages.vulnerable().count(),
                msg=f"[vulnerable_packages] {sbom_filename}",
            )

        vulnerable_dependencies = expected_results.get("vulnerable_dependencies")
        if vulnerable_dependencies:
            self.assertEqual(
                vulnerable_dependencies,
                project.discovereddependencies.vulnerable().count(),
                msg=f"[vulnerable_dependencies] {sbom_filename}",
            )

        vulnerabilities = expected_results.get("vulnerabilities")
        if vulnerabilities:
            self.assertEqual(
                vulnerabilities,
                len(project.vulnerabilities),
                msg=f"[vulnerabilities] {sbom_filename}",
            )

        # Verify that all the expected PURLs are present in the project
        expected_purls = expected_results.get("purls", [])
        if expected_purls:
            purls_diff = benchmark.compare_purls(project, expected_purls)
            formatted_diff = "\n".join(purls_diff)
            self.assertFalse(purls_diff, msg=f"\n{sbom_filename}\n{formatted_diff}")


class ScanPipeIntegrationsSCAToolsTest(ScanPipeIntegrationsBaseTest):
    data = Path(__file__).parent / "data" / "integrations-sca"

    def test_scanpipe_integrations_sca_tools(self):
        """Loop through all SBOM files and run integration checks."""
        for sbom_filename, expected_results in TEST_DATA.items():
            self._test_scanpipe_sca_integrations_tool(sbom_filename, expected_results)
