# Generated by Django 3.1.5 on 2021-02-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0002_run_id_and_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='run_id',
        ),
    ]
