# Generated by Django 3.1.6 on 2021-02-15 10:08

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0003_remove_run_run_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='pipeline',
            new_name='pipeline_name',
        ),
        migrations.AlterField(
            model_name='run',
            name='pipeline_name',
            field=models.CharField(help_text='Identify a registered Pipeline class.', max_length=256),
        ),
    ]
