# Generated by Django 3.1.6 on 2021-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0004_run_pipeline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='input_sources',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
