# Generated by Django 3.2.4 on 2021-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0007_resource_is_binary_is_text_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='is_key_file',
            field=models.BooleanField(default=False),
        ),
    ]
