# Generated by Django 3.2.4 on 2021-07-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0007_resource_is_binary_is_text_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredpackage',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Optional mapping of extra data key/values.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Optional mapping of extra data key/values.'),
        ),
    ]
