# Generated by Django 3.2.4 on 2021-07-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0008_package_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='is_key_file',
            field=models.BooleanField(default=False),
        ),
    ]
