# Generated by Django 3.2.4 on 2021-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0008_package_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredpackage',
            name='dependencies',
            field=models.JSONField(blank=True, default=list, help_text='A list of dependencies for this package.'),
        ),
    ]
