# Generated by Django 3.2.4 on 2021-07-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0009_discoveredpackage_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='is_key_file',
            field=models.BooleanField(default=False),
        ),
    ]
