# Generated by Django 3.2.6 on 2021-08-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0010_codebaseresource_is_key_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='is_media',
            field=models.BooleanField(default=False),
        ),
    ]
