# Generated by Django 3.2.6 on 2021-08-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0011_codebaseresource_is_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='scancodeio_version',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
