# Generated by Django 3.2.9 on 2021-12-07 12:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0013_project_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('target_url', models.URLField(max_length=1024, verbose_name='Target URL')),
                ('sent', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='webhooksubscriptions', to='scanpipe.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
