# Generated by Django 4.0.3 on 2022-04-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0014_webhooksubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebaseresource',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='scanpipe.project'),
        ),
        migrations.AlterField(
            model_name='discoveredpackage',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='scanpipe.project'),
        ),
        migrations.AlterField(
            model_name='projecterror',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='scanpipe.project'),
        ),
        migrations.AlterField(
            model_name='run',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='scanpipe.project'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='scanpipe.project'),
        ),
    ]
