# Generated by Django 4.0.4 on 2022-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0015_alter_codebaseresource_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
