# Generated by Django 4.0.4 on 2022-05-16 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0015_alter_codebaseresource_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='input_sources',
        ),
        migrations.CreateModel(
            name='InputSource',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('source', models.TextField(blank=True, help_text='')),
                ('filename', models.CharField(blank=True, help_text='', max_length=1024)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='scanpipe.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
