# Generated by Django 4.0.5 on 2022-06-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0016_discoveredpackage_package_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveredpackage',
            name='package_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier for this package.', max_length=1024),
        ),
        migrations.AddConstraint(
            model_name='discoveredpackage',
            constraint=models.UniqueConstraint(condition=models.Q(('package_uid', ''), _negated=True), fields=('project', 'package_uid'), name='scanpipe_discoveredpackage_unique_package_uid_within_project'),
        ),
    ]
