# Generated by Django 4.0.5 on 2022-06-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0017_alter_discoveredpackage_package_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
