# Generated by Django 4.0.5 on 2022-07-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0018_codebaseresource_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
