# Generated by Django 4.0.6 on 2022-07-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0018_codebaseresource_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='current_step',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
