# Generated by Django 4.0.6 on 2022-07-27 16:23

from django.db import migrations


def concat_codebaseresource_name_and_extension(apps, schema_editor):
    CodebaseResource = apps.get_model('scanpipe', 'CodebaseResource')
    for cb in CodebaseResource.objects.filter(extension__isnull=False).iterator():
        name = cb.name
        extension = cb.extension
        # The scan_package pipeline was putting the extension in the name field
        # whereas the scan_codebase pipeline did not put the extension in the
        # name field
        if not name.endswith(extension):
            cb.name = f"{name}{extension}"
            cb.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0019_codebaseresource_package_data_discovereddependency'),
    ]

    operations = [
        migrations.RunPython(concat_codebaseresource_name_and_extension),
    ]
