# Generated by Django 4.0.6 on 2022-07-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0020_concat_codebaseresource_name_and_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoveredpackage',
            name='dependencies',
        ),
        migrations.AlterField(
            model_name='codebaseresource',
            name='name',
            field=models.CharField(blank=True, help_text='File or directory name of this resource with its extension.', max_length=255),
        ),
    ]
