# Generated by Django 4.0.6 on 2022-08-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0020_alter_codebaseresource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='package_data',
            field=models.JSONField(blank=True, default=list, help_text='List of Package data detected from this CodebaseResource'),
        ),
    ]
