# Generated by Django 4.1.2 on 2022-11-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0025_remove_discoveredpackage_last_modified_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="current_step",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
