# Generated by Django 4.1 on 2022-08-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0027_remove_discovereddependency_purl"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discovereddependency",
            options={
                "ordering": [
                    "-is_runtime",
                    "-is_resolved",
                    "is_optional",
                    "dependency_uid",
                    "for_package",
                    "datafile_resource",
                ],
                "verbose_name": "discovered dependency",
                "verbose_name_plural": "discovered dependencies",
            },
        ),
    ]
