# Generated by Django 4.1.7 on 2023-03-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0027_remove_webhooksubscription_sent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodebaseRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("identical", "Identical"),
                            ("compiled_to", "Compiled To"),
                        ],
                        max_length=30,
                    ),
                ),
                ("match_type", models.CharField(max_length=30)),
                (
                    "from_resource",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_to",
                        to="scanpipe.codebaseresource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="scanpipe.project",
                    ),
                ),
                (
                    "to_resource",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_from",
                        to="scanpipe.codebaseresource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
