# Generated by Django 4.2 on 2023-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0028_codebaserelation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="codebaseresource",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(fields=["name"], name="scanpipe_co_name_4da308_idx"),
        ),
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(
                fields=["extension"], name="scanpipe_co_extensi_afba0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(
                fields=["programming_language"], name="scanpipe_co_program_5aefaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(fields=["sha1"], name="scanpipe_co_sha1_dd8950_idx"),
        ),
        migrations.AddConstraint(
            model_name="codebaseresource",
            constraint=models.UniqueConstraint(
                fields=("project", "path"),
                name="scanpipe_codebaseresource_unique_path_within_project",
            ),
        ),
    ]
