# Generated by Django 4.2 on 2023-05-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0028_codebaserelation_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(fields=["type"], name="scanpipe_co_type_ea1dd7_idx"),
        ),
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(fields=["size"], name="scanpipe_co_size_a6c452_idx"),
        ),
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(
                fields=["mime_type"], name="scanpipe_co_mime_ty_639d1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(
                fields=["compliance_alert"], name="scanpipe_co_complia_bbbeba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(
                fields=["is_binary"], name="scanpipe_co_is_bina_036bd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(
                fields=["is_text"], name="scanpipe_co_is_text_0ac1c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discovereddependency",
            index=models.Index(fields=["scope"], name="scanpipe_di_scope_17c335_idx"),
        ),
        migrations.AddIndex(
            model_name="discovereddependency",
            index=models.Index(
                fields=["is_runtime"], name="scanpipe_di_is_runt_02f548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discovereddependency",
            index=models.Index(
                fields=["is_optional"], name="scanpipe_di_is_opti_ac7015_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discovereddependency",
            index=models.Index(
                fields=["is_resolved"], name="scanpipe_di_is_reso_10570c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredpackage",
            index=models.Index(fields=["type"], name="scanpipe_di_type_56af64_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveredpackage",
            index=models.Index(
                fields=["namespace"], name="scanpipe_di_namespa_0da988_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredpackage",
            index=models.Index(fields=["name"], name="scanpipe_di_name_d5f3b8_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveredpackage",
            index=models.Index(
                fields=["license_expression"], name="scanpipe_di_license_e8ce32_idx"
            ),
        ),
    ]
