# Generated by Django 4.2 on 2023-05-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0029_codebaseresource_scanpipe_co_type_ea1dd7_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="configuration",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
