# Generated by Django 4.2 on 2023-04-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0030_codebaserelation_scanpipe_co_relatio_40d26d_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(fields=["status"], name="scanpipe_co_status_20d02b_idx"),
        ),
    ]
