# Generated by Django 4.2 on 2023-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0031_codebaseresource_scanpipe_co_status_20d02b_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="codebaseresource",
            index=models.Index(fields=["tag"], name="scanpipe_co_tag_16a73d_idx"),
        ),
    ]
