# Generated by Django 4.2 on 2023-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0032_remove_codebaseresource_license_expressions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codebaseresource",
            name="detected_license_expression",
            field=models.TextField(blank=True, help_text=""),
        ),
        migrations.AlterField(
            model_name="codebaseresource",
            name="detected_license_expression_spdx",
            field=models.TextField(blank=True, help_text=""),
        ),
        migrations.AlterField(
            model_name="codebaseresource",
            name="percentage_of_license_text",
            field=models.FloatField(blank=True, help_text="", null=True),
        ),
    ]
