# Generated by Django 4.2 on 2023-04-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0032_codebaseresource_scanpipe_co_tag_16a73d_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="codebaserelation",
            name="scanpipe_co_match_t_62bd20_idx",
        ),
        migrations.RenameField(
            model_name="codebaserelation",
            old_name="match_type",
            new_name="map_type",
        ),
        migrations.AddIndex(
            model_name="codebaserelation",
            index=models.Index(
                fields=["map_type"], name="scanpipe_co_map_typ_3a191c_idx"
            ),
        ),
    ]
