# Generated by Django 4.2 on 2023-04-28 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "scanpipe",
            "0033_remove_codebaserelation_scanpipe_co_match_t_62bd20_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="codebaserelation",
            name="scanpipe_co_relatio_40d26d_idx",
        ),
        migrations.RemoveField(
            model_name="codebaserelation",
            name="relationship",
        ),
    ]
