# Generated by Django 4.2 on 2023-04-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "scanpipe",
            "0034_remove_codebaserelation_scanpipe_co_relatio_40d26d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="codebaserelation",
            constraint=models.UniqueConstraint(
                fields=("from_resource", "to_resource", "map_type"),
                name="scanpipe_codebaserelation_unique_relation",
            ),
        ),
    ]
