# Generated by Django 4.2.2 on 2023-06-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0035_set_projects_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=110, unique=True),
        ),
    ]
