# Generated by Django 4.2.3 on 2023-08-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0039_discoveredpackage_compliance_alert_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discovereddependency",
            name="affected_by_vulnerabilities",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
