# Generated by Django 4.2.3 on 2023-07-12 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0042_projecterror_to_projectmessage_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectError",
        ),
    ]
