# Generated by Django 4.2.4 on 2023-08-24 15:05

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration originally created the django-taggit-backed ``UUIDTaggedItem``
    model and the ``Project.labels`` TaggableManager field.
    django-taggit was removed in favor of a plain ``Project.labels`` JSONField. 
    Its operations were emptied out so this migration (and the app's migration graph) 
    no longer depends on the "taggit" app, which allows
    fresh installs to migrate without django-taggit installed. Databases where this
    migration already ran keep their existing tables untouched by this change, as
    already-applied migrations are not re-executed.
    """

    dependencies = [
        ("scanpipe", "0043_delete_projecterror"),
    ]

    operations = []
