# Generated by Django 4.2.4 on 2023-08-29 15:32

from django.db import migrations


def migrate_scan_codebase_package_run(apps, schema_editor):
    Run = apps.get_model("scanpipe", "Run")
    qs = Run.objects.filter(pipeline_name="scan_codebase_package")
    qs.update(pipeline_name="scan_codebase_packages")


def reverse_migrate_scan_codebase_package_run(apps, schema_editor):
    Run = apps.get_model("scanpipe", "Run")
    qs = Run.objects.filter(pipeline_name="scan_codebase_packages")
    qs.update(pipeline_name="scan_codebase_package")


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0044_uuidtaggeditem_project_labels"),
    ]

    operations = [
        migrations.RunPython(
            migrate_scan_codebase_package_run,
            reverse_code=reverse_migrate_scan_codebase_package_run,
        ),
    ]
