# Generated by Django 4.2.4 on 2023-09-13 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0044_remove_discovereddependency_name_and_more"),
        ("scanpipe", "0045_scan_codebase_packages_data"),
    ]

    operations = []
