# Generated by Django 4.2.4 on 2023-09-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0045_scan_codebase_packages_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredpackage",
            name="tag",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="discoveredpackage",
            index=models.Index(fields=["tag"], name="scanpipe_di_tag_a8f4a5_idx"),
        ),
    ]
