# Generated by Django 4.2.5 on 2023-10-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0046_discoveredpackage_tag"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="discoveredpackage",
            index=models.Index(
                fields=["version"], name="scanpipe_di_version_44de05_idx"
            ),
        ),
    ]
