# Generated by Django 4.2.6 on 2023-10-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0047_discoveredpackage_scanpipe_di_version_44de05_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredpackage",
            name="status",
            field=models.CharField(
                blank=True, help_text="Analysis status for this package.", max_length=30
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredpackage",
            index=models.Index(fields=["status"], name="scanpipe_di_status_93e710_idx"),
        ),
    ]
