# Generated by Django 5.0.1 on 2024-02-02 11:42

import scanpipe.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanpipe", "0051_rename_pipelines_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="selected_groups",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[scanpipe.models.validate_none_or_list],
            ),
        ),
    ]
