# Generated by Django 5.0.1 on 2024-01-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0051_rename_pipelines_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
