# Generated by Django 5.0.2 on 2024-03-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0052_project_is_marked_for_deletion"),
        ("scanpipe", "0053_restructure_pipelines_data"),
    ]

    operations = []
