# Generated by Django 5.0.3 on 2024-05-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0055_discoveredpackage_datafile_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="scancodeio_version",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
