# Generated by Django 5.0.4 on 2024-05-17 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0057_rename_symbol_collection_pipelines"),
    ]

    operations = [
        migrations.AddField(
            model_name="discovereddependency",
            name="resolved_to",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The resolved package for this dependency. If empty, it indicates the dependency is unresolved.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_dependencies",
                to="scanpipe.discoveredpackage",
            ),
        ),
        migrations.AlterField(
            model_name="discovereddependency",
            name="datafile_resource",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The codebase resource (e.g., manifest or lockfile) that declares this dependency.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="declared_dependencies",
                to="scanpipe.codebaseresource",
            ),
        ),
        migrations.AlterField(
            model_name="discovereddependency",
            name="for_package",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The package that declares this dependency.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="declared_dependencies",
                to="scanpipe.discoveredpackage",
            ),
        ),
    ]
