# Generated by Django 5.0.6 on 2024-05-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0058_discovereddependency_resolved_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codebaseresource",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Analysis status for this resource.",
                max_length=50,
            ),
        ),
    ]
