# Generated by Django 5.0.6 on 2024-06-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0059_alter_codebaseresource_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discovereddependency",
            old_name="resolved_to",
            new_name="resolved_to_package",
        ),
        migrations.AlterField(
            model_name="discovereddependency",
            name="resolved_to_package",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The resolved package for this dependency. If empty, it indicates the dependency is unresolved.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_from_dependencies",
                to="scanpipe.discoveredpackage",
            ),
        ),
        migrations.AddField(
            model_name="discoveredpackage",
            name="children_packages",
            field=models.ManyToManyField(
                related_name="parent_packages",
                through="scanpipe.DiscoveredDependency",
                to="scanpipe.discoveredpackage",
            ),
        ),
    ]
