# Generated by Django 5.0.6 on 2024-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0060_discovereddependency_renames"),
    ]

    operations = [
        migrations.AddField(
            model_name="codebaseresource",
            name="is_legal",
            field=models.BooleanField(
                default=False,
                help_text="True if this file is likely a legal, license-related file such as a COPYING or LICENSE file.",
            ),
        ),
        migrations.AddField(
            model_name="codebaseresource",
            name="is_manifest",
            field=models.BooleanField(
                default=False,
                help_text="True if this file is likely a package manifest file such as a Maven pom.xml or an npm package.json",
            ),
        ),
        migrations.AddField(
            model_name="codebaseresource",
            name="is_readme",
            field=models.BooleanField(
                default=False, help_text="True if this file is likely a README file."
            ),
        ),
        migrations.AddField(
            model_name="codebaseresource",
            name="is_top_level",
            field=models.BooleanField(
                default=False,
                help_text="True if this file is top-level file located either at the root of a package or in a well-known common location.",
            ),
        ),
        migrations.AlterField(
            model_name="codebaseresource",
            name="is_key_file",
            field=models.BooleanField(
                default=False,
                help_text="True if this file is top-level file and either a legal, readme or manifest file.",
            ),
        ),
    ]
