# Generated by Django 5.0.6 on 2024-07-01 05:14

import scanpipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0061_codebaseresource_is_legal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="selected_steps",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[scanpipe.models.validate_none_or_list],
            ),
        ),
    ]
