# Generated by Django 5.0.6 on 2024-07-03 09:59

import scanpipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0062_dependency_resolver_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='selected_steps',
            field=models.JSONField(blank=True, null=True, validators=[scanpipe.models.validate_none_or_list]),
        ),
    ]
