# Generated by Django 5.0.7 on 2024-07-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0065_webhookdelivery_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhooksubscription',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='webhooksubscription',
            name='delivery_error',
        ),
        migrations.RemoveField(
            model_name='webhooksubscription',
            name='response_status_code',
        ),
        migrations.RemoveField(
            model_name='webhooksubscription',
            name='response_text',
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='include_results',
            field=models.BooleanField(default=False, help_text='Include the entire results data in the payload.'),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='include_summary',
            field=models.BooleanField(default=False, help_text='Include the entire summary data in the payload.'),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the Webhook is currently active and should be triggered.'),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='trigger_on_each_run',
            field=models.BooleanField(default=False, help_text='Trigger the Webhook after each individual pipeline run instead of only after all runs are completed.'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the Webhook subscription was created.'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='target_url',
            field=models.URLField(help_text='The URL to which the POST request will be sent when the Webhook is triggered.', max_length=1024, verbose_name='Target URL'),
        ),
    ]
