# Generated by Django 5.0.7 on 2024-08-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0066_alter_webhooksubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredpackage',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
