# Generated by Django 5.1.1 on 2025-05-10 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0067_discoveredpackage_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageArchive',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('checksum_sha256', models.CharField(db_index=True, help_text='SHA256 checksum of the package archive file.', max_length=64, unique=True)),
                ('storage_path', models.CharField(help_text='Path to the stored archive file (e.g., file:///path/to/file).', max_length=1024)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date when the archive was added to storage.')),
            ],
            options={
                'indexes': [models.Index(fields=['checksum_sha256'], name='checksum_idx')],
            },
        ),
        migrations.CreateModel(
            name='DownloadedPackage',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('url', models.URLField(blank=True, db_index=True, help_text='URL from which the package was downloaded, if applicable.', max_length=1024)),
                ('filename', models.CharField(help_text='Name of the package file.', max_length=255)),
                ('download_date', models.DateTimeField(auto_now_add=True, help_text='Date when the package was downloaded or added.')),
                ('scan_log', models.TextField(blank=True, help_text='Log output from scanning the package.')),
                ('scan_date', models.DateTimeField(blank=True, help_text='Date when the package was scanned.', null=True)),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='downloadedpackages', to='scanpipe.project')),
                ('package_archive', models.ForeignKey(help_text='The stored archive file associated with this package.', on_delete=django.db.models.deletion.CASCADE, to='scanpipe.packagearchive')),
            ],
            options={
                'indexes': [models.Index(fields=['url'], name='url_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('url__gt', '')), fields=('url', 'project'), name='scanpipe_downloadedpackage_unique_url_project')],
            },
        ),
    ]
