# Generated by Django 5.1.1 on 2025-03-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0067_discoveredpackage_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='is_whiteout',
            field=models.BooleanField(default=False, help_text='Indicates if this resource is a white-out file in a container scan.'),
        ),
    ]
