# Generated by Django 5.0.7 on 2024-10-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0067_discoveredpackage_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discovereddependency",
            options={
                "ordering": [
                    "-is_runtime",
                    "-is_pinned",
                    "is_optional",
                    "dependency_uid",
                    "for_package",
                    "datafile_resource",
                    "datasource_id",
                ],
                "verbose_name": "discovered dependency",
                "verbose_name_plural": "discovered dependencies",
            },
        ),
        migrations.RemoveIndex(
            model_name="discovereddependency",
            name="scanpipe_di_is_reso_10570c_idx",
        ),
        migrations.RenameField(
            model_name="discovereddependency",
            old_name="is_resolved",
            new_name="is_pinned",
        ),
        migrations.AddIndex(
            model_name="discovereddependency",
            index=models.Index(
                fields=["is_pinned"], name="scanpipe_di_is_pinn_5667b2_idx"
            ),
        ),
    ]
