# Generated by Django 5.0.7 on 2024-08-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0067_discoveredpackage_notes'),
        ('scanpipe', '0067_packagescore_scorecardcheck'),
    ]

    operations = [
    ]
