# Generated by Django 5.0.7 on 2024-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0067_discoveredpackage_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_purl',
            field=models.CharField(blank=True, help_text='Project Package URL.', max_length=2048),
        ),
    ]
