# Generated by Django 5.0.7 on 2024-11-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanpipe", "0068_rename_discovered_dependencies_attribute"),
    ]

    operations = [
        migrations.RenameField(
            model_name="run",
            old_name="selected_groups",
            new_name="selected_options",
        ),
    ]
