# Generated by Django 5.1.1 on 2025-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0068_packagearchive_downloadedpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagearchive',
            name='package_file',
            field=models.FileField(blank=True, help_text='The actual package archive file (e.g., ZIP or TAR).', null=True, upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='packagearchive',
            name='storage_path',
            field=models.CharField(blank=True, help_text='Path to the stored archive file (e.g., file:///path/to/file).', max_length=1024),
        ),
    ]
