# Generated by Django 5.1.3 on 2024-11-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0068_rename_discovered_dependencies_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='purl',
            field=models.CharField(blank=True, help_text='Package URL for the project, used for pushing project scan result to FederatedCode. This should be the PURL of the input.', max_length=2048),
        ),
    ]
