# Generated by Django 5.1.5 on 2025-03-03 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0069_project_purl'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredpackage',
            name='analysis_subproject',
            field=models.OneToOneField(blank=True, editable=False, help_text='Sub-project dedicated to analyzing this package.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_package', to='scanpipe.project'),
        ),
    ]
