# Generated by Django 5.1.1 on 2025-05-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0069_packagearchive_package_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_local_storage',
            field=models.BooleanField(default=False, help_text='Store packages locally if enabled.'),
        ),
        migrations.AlterField(
            model_name='packagearchive',
            name='package_file',
            field=models.FileField(blank=True, help_text='The actual package archive file ( ZIP or TAR).', null=True, upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='packagearchive',
            name='storage_path',
            field=models.CharField(blank=True, help_text='Path to the stored archive file', max_length=1024),
        ),
    ]
