# Generated by Django 5.1.8 on 2025-04-16 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0071_discovereddependency_uuid_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovereddependency',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
