# Generated by Django 5.0.7 on 2024-07-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0066_alter_webhooksubscription_options_and_more'),
        ('scanpipe', '0071_remove_discoveredpackage_scores_and_more'),
    ]

    operations = [
    ]
