# Generated by Django 5.1.11 on 2025-06-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0072_discovereddependency_uuid_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='sha1_git',
            field=models.CharField(blank=True, help_text='SHA1 checksum generated by Git, hex-encoded.', max_length=40, verbose_name='SHA1_git'),
        ),
    ]
