# Generated by Django 5.1.9 on 2025-06-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0072_discovereddependency_uuid_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='ancestor',
            field=models.CharField(blank=True, help_text="Path of the immediate parent directory of this resource. Its '.' for top-level resources.", max_length=2000, null=True),
        ),
        migrations.AddIndex(
            model_name='codebaseresource',
            index=models.Index(fields=['project', 'ancestor'], name='scanpipe_co_project_f1a160_idx'),
        ),
    ]
