# Generated by Django 5.1.9 on 2025-06-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0072_discovereddependency_uuid_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='parent_path',
            field=models.CharField(blank=True, help_text='Path of the immediate parent directory of a resource. For top level resources the value is set to None', max_length=2000, null=True),
        ),
        migrations.AddIndex(
            model_name='codebaseresource',
            index=models.Index(fields=['project', 'parent_path'], name='scanpipe_co_project_008448_idx'),
        ),
    ]
