# Generated by Django 5.1.9 on 2025-06-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0073_add_sha1_git_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseresource',
            name='parent_path',
            field=models.CharField(blank=True, help_text='The path of the resource\'s parent directory. Set to None for top-level (root) resources. Used to efficiently retrieve a directory\'s contents.', max_length=2000),
        ),
        migrations.AddIndex(
            model_name='codebaseresource',
            index=models.Index(fields=['project', 'parent_path'], name='scanpipe_co_project_008448_idx'),
        ),
    ]
