# Generated by Django 6.0.3 on 2026-03-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0076_discoveredpackagescore_scorecardcheck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveredpackage',
            name='children_packages',
            field=models.ManyToManyField(related_name='parent_packages', through='scanpipe.DiscoveredDependency', through_fields=('for_package', 'resolved_to_package'), to='scanpipe.discoveredpackage'),
        ),
    ]
