# Generated by Django 6.0.3 on 2026-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0079_apitoken_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredpackage',
            name='concluded_license_expression',
            field=models.TextField(blank=True, help_text='TODO'),
        ),
        migrations.AddField(
            model_name='discoveredpackage',
            name='concluded_license_expression_spdx',
            field=models.TextField(blank=True, help_text='The SPDX license expression for this package converted from its concluded_license_expression.'),
        ),
        migrations.AddIndex(
            model_name='discoveredpackage',
            index=models.Index(fields=['concluded_license_expression'], name='scanpipe_di_conclud_8c4528_idx'),
        ),
    ]
