# Generated by Django 6.0.3 on 2026-04-14 11:10

from django.db import migrations
from django.db.models import Q


def add_advisory_id(apps, schema_editor):
    """Copy vulnerability_id to advisory_id in affected_by_vulnerabilities entries."""
    DiscoveredPackage = apps.get_model("scanpipe", "DiscoveredPackage")
    DiscoveredDependency = apps.get_model("scanpipe", "DiscoveredDependency")
    EMPTY_VALUES = [None, [], ""]

    vulnerable = ~Q(affected_by_vulnerabilities__in=EMPTY_VALUES)

    for model in [DiscoveredPackage, DiscoveredDependency]:
        for instance in model.objects.filter(vulnerable):
            for entry in instance.affected_by_vulnerabilities:
                if "advisory_id" not in entry:
                    entry["advisory_id"] = entry.get("vulnerability_id", "")
            instance.save(update_fields=["affected_by_vulnerabilities"])


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0079_apitoken_data'),
    ]

    operations = [
        migrations.RunPython(
            add_advisory_id,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
