# Generated by Django 6.0.5 on 2026-06-22 10:38

from django.db import migrations, models
from django.db.models import Count
from django.db.models import IntegerField
from django.db.models import OuterRef
from django.db.models import Subquery
from django.db.models.functions import Coalesce


def backfill_project_counts(apps, schema_editor):
    """Backfill denormalized count fields for all existing projects in a single query."""
    Project = apps.get_model("scanpipe", "Project")
    CodebaseResource = apps.get_model("scanpipe", "CodebaseResource")
    DiscoveredPackage = apps.get_model("scanpipe", "DiscoveredPackage")
    DiscoveredDependency = apps.get_model("scanpipe", "DiscoveredDependency")
    ProjectMessage = apps.get_model("scanpipe", "ProjectMessage")
    CodebaseRelation = apps.get_model("scanpipe", "CodebaseRelation")

    def subquery_count(model):
        return Coalesce(
            Subquery(
                model.objects.filter(project=OuterRef("pk"))
                .values("project")
                .annotate(count=Count("pk"))
                .values("count"),
                output_field=IntegerField(),
            ),
            0,
        )

    Project.objects.update(
        resource_count=subquery_count(CodebaseResource),
        package_count=subquery_count(DiscoveredPackage),
        dependency_count=subquery_count(DiscoveredDependency),
        message_count=subquery_count(ProjectMessage),
        relation_count=subquery_count(CodebaseRelation),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0080_vulnerablecode_v3_data'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dependency_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='message_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='package_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='relation_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='resource_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(backfill_project_counts, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_archived', '-created_date'], name='scanpipe_pr_is_arch_5fe32b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['resource_count'], name='scanpipe_pr_resourc_24e71a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['package_count'], name='scanpipe_pr_package_ad079b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['dependency_count'], name='scanpipe_pr_depende_14398a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['message_count'], name='scanpipe_pr_message_6070e1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['relation_count'], name='scanpipe_pr_relatio_42d666_idx'),
        ),
    ]
