# Generated by Django 6.0.5 on 2026-06-22 08:29

from django.db import migrations
from django.db import models
from django.db.models import Count
from django.db.models import IntegerField
from django.db.models import OuterRef
from django.db.models import Subquery
from django.db.models.functions import Coalesce


def backfill_project_counts(apps, schema_editor):
    """Backfill denormalized count fields for all existing projects in a single query."""
    Project = apps.get_model("scanpipe", "Project")
    CodebaseResource = apps.get_model("scanpipe", "CodebaseResource")
    DiscoveredPackage = apps.get_model("scanpipe", "DiscoveredPackage")
    DiscoveredDependency = apps.get_model("scanpipe", "DiscoveredDependency")
    ProjectMessage = apps.get_model("scanpipe", "ProjectMessage")

    codebaseresources_subquery = (
        CodebaseResource.objects.filter(project=OuterRef("pk"))
        .values("project")
        .annotate(count=Count("pk"))
        .values("count")
    )
    discoveredpackages_subquery = (
        DiscoveredPackage.objects.filter(project=OuterRef("pk"))
        .values("project")
        .annotate(count=Count("pk"))
        .values("count")
    )
    discovereddependencies_subquery = (
        DiscoveredDependency.objects.filter(project=OuterRef("pk"))
        .values("project")
        .annotate(count=Count("pk"))
        .values("count")
    )
    projectmessages_subquery = (
        ProjectMessage.objects.filter(project=OuterRef("pk"))
        .values("project")
        .annotate(count=Count("pk"))
        .values("count")
    )

    Project.objects.update(
        codebaseresources_count=Coalesce(
            Subquery(codebaseresources_subquery, output_field=IntegerField()), 0
        ),
        discoveredpackages_count=Coalesce(
            Subquery(discoveredpackages_subquery, output_field=IntegerField()), 0
        ),
        discovereddependencies_count=Coalesce(
            Subquery(discovereddependencies_subquery, output_field=IntegerField()), 0
        ),
        projectmessages_count=Coalesce(
            Subquery(projectmessages_subquery, output_field=IntegerField()), 0
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0080_vulnerablecode_v3_data'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='codebaseresources_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='discovereddependencies_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='discoveredpackages_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='projectmessages_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(backfill_project_counts, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['codebaseresources_count'], name='scanpipe_pr_codebas_86003c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['discoveredpackages_count'], name='scanpipe_pr_discove_8e5912_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['discovereddependencies_count'], name='scanpipe_pr_discove_3a95e9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['projectmessages_count'], name='scanpipe_pr_project_006339_idx'),
        ),
    ]
