# Generated by Django 6.0.5 on 2026-07-02 13:07

from django.db import migrations, models


def populate_labels_json(apps, schema_editor):
    """
    Copy the existing django-taggit labels into the new ``labels_json`` field.
    Raw SQL is used against the legacy ``scanpipe_uuidtaggeditem`` and
    ``taggit_tag`` tables since the "taggit" app is no longer installed and has no
    ORM model available in this migration state.
    """
    Project = apps.get_model("scanpipe", "Project")

    with schema_editor.connection.cursor() as cursor:
        existing_tables = schema_editor.connection.introspection.table_names(cursor)
        if "scanpipe_uuidtaggeditem" not in existing_tables:
            return

        cursor.execute(
            "SELECT tagged_item.object_id, tag.name "
            "FROM scanpipe_uuidtaggeditem AS tagged_item "
            "JOIN taggit_tag AS tag ON tag.id = tagged_item.tag_id "
            "ORDER BY tag.name"
        )
        rows = cursor.fetchall()

    if not rows:
        return

    labels_by_project_id = {}
    for project_id, label in rows:
        labels_by_project_id.setdefault(project_id, []).append(label)

    projects = [
        Project(pk=project_id, labels_json=labels)
        for project_id, labels in labels_by_project_id.items()
    ]
    Project.objects.bulk_update(projects, ["labels_json"], batch_size=1000)


def drop_legacy_taggit_tables(apps, schema_editor):
    """Drop the legacy django-taggit tables now that their data has been migrated."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS scanpipe_uuidtaggeditem")
        # The default django-taggit through table, unused since Project.labels used
        # the custom UUIDTaggedItem through table, but still created by taggit's own
        # migrations.
        cursor.execute("DROP TABLE IF EXISTS taggit_taggeditem")
        cursor.execute("DROP TABLE IF EXISTS taggit_tag")


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0081_project_count_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='labels_json',
            field=models.JSONField(
                blank=True, 
                default=list, 
                help_text='A list of labels for this project.',
            ),
        ),
        migrations.RunPython(populate_labels_json, migrations.RunPython.noop),
        migrations.RunPython(drop_legacy_taggit_tables, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='project',
            old_name='labels_json',
            new_name='labels',
        ),
    ]
