# Generated by Django 4.0.6 on 2022-08-11 01:12

from django.db import migrations
from django.db.models import F, Q

from packageurl import PackageURL


def set_discovereddependency_purl_fields(apps, schema_editor):
    DiscoveredDependency = apps.get_model('scanpipe', 'DiscoveredDependency')
    qs = DiscoveredDependency.objects.filter(Q(dependency_uid__isnull=False) & ~Q(dependency_uid__exact=""))
    qs.update(**PackageURL.from_string(F("dependency_uid")).to_dict())


class Migration(migrations.Migration):

    dependencies = [
        ('scanpipe', '0022_alter_discovereddependency_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_discovereddependency_purl_fields),
    ]
