# Generated by Django 3.1.1 on 2020-09-09 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('task_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('task_start_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('task_end_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('task_exitcode', models.IntegerField(blank=True, editable=False, null=True)),
                ('task_output', models.TextField(blank=True, editable=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('uri', models.CharField(db_index=True, max_length=2048, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+-_]+://[\\S]+$'), code='invalid', message='Enter a valid URI.')], verbose_name='URI')),
                ('output_file', models.FileField(max_length=350, null=True, upload_to='')),
                ('scancode_version', models.CharField(blank=True, db_index=True, max_length=50)),
                ('filename', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sha1', models.CharField(blank=True, db_index=True, help_text='SHA1 checksum hex-encoded, as in sha1sum.', max_length=40, null=True, verbose_name='SHA1')),
                ('md5', models.CharField(blank=True, db_index=True, help_text='MD5 checksum hex-encoded, as in md5sum.', max_length=32, null=True, verbose_name='MD5')),
                ('size', models.BigIntegerField(blank=True, db_index=True, help_text='Size in bytes.', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True, serialize=False)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Summary data extracted from the Scan results.')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(editable=False, verbose_name='User UUID')),
                ('target_url', models.URLField(max_length=1024, verbose_name='Target URL')),
                ('sent', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scan')),
            ],
        ),
    ]
