name: Generate SBOM with Trivy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main


permissions:
  contents: write

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'image'
          image-ref: 'python:3.13-slim'
          format: 'cyclonedx'
          output: 'dependency-results.sbom.cdx.json'
          scanners: 'vuln,license'
          version: 'latest'

      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: '${{ github.workspace }}/dependency-results.sbom.json'
          retention-days: 20 # 90 is the default
