name: Generate SBOMS

on: [push]

jobs:
  generate-sboms:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure scancode-inputs directory exists
        run: mkdir -p scancode-inputs

      - name: Build the Docker image from local Dockerfile
        run: docker build -t local-image .

      - name: Run pip freeze inside the built Docker container
        run: docker run --rm local-image pip freeze --all --exclude scancodeio > scancode-inputs/requirements.txt

      - name: Collect all .ABOUT files in the scancodeio/ directory
        run: |
          mkdir -p scancode-inputs/about-files  # Create the directory if it doesn't exist
          find scancodeio/ -type f -name "*.ABOUT" -exec cp {} scancode-inputs/about-files/ \;

      - name: Resolve the dependencies using ScanCode-action
        uses: nexB/scancode-action@main
        with:
          pipelines: "resolve_dependencies:DynamicResolver"
          scancodeio-repo-branch: main
