name: Lint Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      
      - name: Run Ruff linter
        run: ruff check
      
      - name: Run Ruff formatter check
        run: ruff format --check
      
      - name: Check documentation format
        run: doc8 --max-line-length 100 --ignore-path docs/_build/ --quiet docs/
      
      - name: Check Django deployment settings
        run: python manage.py check --deploy

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      
      - name: Install bandit
        run: pip install bandit
      
      - name: Run bandit
        run: bandit -r scanpipe scancodeio -x tests,venv,.venv