name: Build aboutcode.pipeline Python distributions and publish on PyPI

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "aboutcode.pipeline/v*.*.*"

jobs:
  build-and-publish:
    name: Build and publish library to PyPI
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install flot
        run: python -m pip install flot --user

      - name: Build a binary wheel and a source tarball
        run:  python -m flot --pyproject pipeline-pyproject.toml --sdist --wheel --output-dir dist/

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload built archives
        uses: actions/upload-artifact@v4
        with:
          name: pypi_archives
          path: dist/*

      # - name: Create a GitHub release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     files: dist/*
