name: Generate SBOM with Vuls and load into ScanCode.io

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  IMAGE_REFERENCE: "alpine:3.17"

jobs:
  generate-and-load-sbom:
    runs-on: ubuntu-24.04
    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl unzip sudo

      - name: Install Vuls
        run: |
          git clone https://github.com/vulsio/vulsctl.git
          cd vulsctl/docker/

      - name: Create Vuls config
        run: |
          cat <<EOF > config.toml
          [servers]
          [servers.local]
          host = "127.0.0.1"
          user = "runner"
          password = ""
          sudo = true
          EOF

#      - name: Run Vuls configtest
#        run: ./scan.sh configtest

      - name: Run Vuls scan
        run: ./scan.sh local

#      - name: Prepare Vuls config.toml
#        run: |
#          mkdir -p ./vuls-config
#          cat > ./vuls-config/config.toml <<'EOF'
#          [servers]
#
#          [servers.cpescan]
#          type = "pseudo"
#          cpeNames = [
#              "cpe:/o:fortinet:fortios:4.3.0",
#          ]
#          EOF

#      # Pull Vuls image
#      - name: Pull Vuls Docker image
#        run: docker pull vuls/vuls:latest
#
#      # Run Vuls scan
#      - name: Run Vuls scan
#        run: |
#          mkdir -p ./results
#          docker run --rm \
#            -v $PWD:/workdir \
#            -w /workdir \
#            -u $(id -u):$(id -g) \
#            -e VULS_HOME=/workdir/.vuls \
#            vuls/vuls scan \
#            -config=/workdir/vuls-config/config.toml \
#            -results-dir=/workdir/results
#
#      - name: Upload Vuls scan report
#        uses: actions/upload-artifact@v4
#        with:
#          name: vuls-scan-report
#          path: results
#          retention-days: 20
