name: Generate SBOM with OSV-Scanner and load into ScanCode.io

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # to fetch code (actions/checkout)
  contents: read

env:
  IMAGE_REFERENCE: "python:3.13.0-slim"

#jobs:
#  generate-and-load-sbom:
#    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.2.1
#    with:
#      scan-args: |-
#        image
#        python:3.13.0-slim
#        --format
#        cyclonedx-1-5

jobs:
  generate-and-load-sbom:
    runs-on: ubuntu-24.04

    steps:
      - name: Docker
        run: |
          docker --version
          docker pull python:3.13.0-slim
          docker save python:3.13.0-slim > python_s3.13.0-slim.tar

      - name: Run OSV Scanner
        uses: docker://ghcr.io/google/osv-scanner-action:v2.2.1
        with:
          args: scan image python_s3.13.0-slim.tar --format cyclonedx-1-5
