name: Generate SBOM with Anchore Grype and load into ScanCode.io

# This workflow:
#  1. Generates a CycloneDX SBOM for a container image using Anchore Grype.
#  2. Uploads the SBOM as a GitHub artifact for future inspection.
#  3. Loads the SBOM into ScanCode.io for further analysis.
#  4. Runs assertions to verify that the SBOM was properly processed in ScanCode.io.
#
# It runs on demand, and once a week (scheduled).

on:
  workflow_dispatch:
  schedule:
    # Run once a week (every 7 days) at 00:00 UTC on Sunday
    - cron: "0 0 * * 0"

permissions:
  contents: read

env:
  IMAGE_REFERENCE: "python:3.13.0-slim"
  EXPECTED_PACKAGE: 3200
  EXPECTED_VULNERABLE_PACKAGE: 40
  EXPECTED_DEPENDENCY: 220

jobs:
  generate-and-load-sbom:
    runs-on: ubuntu-24.04
    steps:
      - name: Generate CycloneDX SBOM with Anchore Grype scanner
        uses: anchore/scan-action@v6
        with:
          image: ${{ env.IMAGE_REFERENCE }}
          output-format: cyclonedx-json
          output-file: "anchore-grype-sbom.cdx.json"
          fail-build: false

      - name: Upload SBOM as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: anchore-sbom-report
          path: "anchore-grype-sbom.cdx.json"
          retention-days: 20

      - name: Import SBOM into ScanCode.io
        uses: aboutcode-org/scancode-action@main
        with:
          pipelines: "load_sbom"
          inputs-path: "anchore-grype-sbom.cdx.json"
          scancodeio-repo-branch: "main"

      - name: Verify SBOM Analysis Results in ScanCode.io
        shell: bash
        run: |
          scanpipe verify-project \
            --project scancode-action \
            --packages ${{ env.EXPECTED_PACKAGE }} \
            --vulnerable-packages ${{ env.EXPECTED_VULNERABLE_PACKAGE }} \
            --dependencies ${{ env.EXPECTED_DEPENDENCY }}
