name: Generate SBOM with Vuls and load into ScanCode.io

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  IMAGE_REFERENCE: "alpine:3.17"

jobs:
  generate-and-load-sbom:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:24.04.2
    steps:
      - name: Prepare Vuls config.toml
        run: |
          mkdir -p vuls
          cat > vuls/config.toml <<'EOF'
          [servers]
          
          [servers.localhost]
          host = "localhost"
          port = "local"
          EOF

      - name: Run Vuls configtest
        run: |
          docker run --rm \
            -v $PWD/vuls:/vuls \
            vuls/vuls configtest -config=/vuls/config.toml

      - name: Run Vuls scan
        run: |
          mkdir -p $PWD/vuls/result
          docker run --rm \
            -v $PWD/vuls:/vuls \
            -e VULS_RESULT_DIR=/vuls/result \
            vuls/vuls scan -config=/vuls/config.toml

      - name: Run Vuls report
        run: |
          docker run --rm \
            -v $PWD/vuls:/vuls \
            -e VULS_RESULT_DIR=/vuls/result \
            vuls/vuls report -config=/vuls/config.toml -format-cyclonedx-json

      - name: DEBUG
        run: |
          ls -la vuls/result
          ls -la vuls/results
