name: Generate SBOM with Vuls and load into ScanCode.io

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  IMAGE_REFERENCE: "alpine:3.17"

jobs:
  generate-and-load-sbom:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare Vuls image scan config.toml
        run: |
          mkdir -p ./vuls-config
          cat > ./vuls-config/config.toml <<'EOF'
          [servers]
          [servers.image]
          type="pseudo"

            [servers.image.images.localpython]
            name="${{ env.IMAGE_REFERENCE }}"
            tag="latest"
          EOF

      - name: Pull Vuls image
        run: docker pull vuls/vuls:latest

      - name: Run Vuls Image Scan
        run: |
          mkdir -p ./results
          docker run --rm \
            -u $(id -u):$(id -g) \
            -v $PWD:/workdir \
            -w /workdir \
            vuls/vuls scan -config=/workdir/vuls-config/config.toml -results-dir=/workdir/results

      - name: Upload Vuls report as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vuls-image-scan-report
          path: results
          retention-days: 20
