name: Generate SBOM with OSV-Scanner and load into ScanCode.io

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # to fetch code (actions/checkout)
  contents: read

env:
  IMAGE_REFERENCE: "python:3.13.0-slim"

jobs:
  generate-and-load-sbom:
    runs-on: ubuntu-24.04

    steps:
#      - name: Docker
#        run: |
#          docker pull alpine:3.17.0
#          docker save alpine:3.17.0 > alpine_3.17.0.tar

      - name: Install OSV-Scanner
        run: |
          curl -sLO https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64
          chmod +x osv-scanner_linux_amd64
          sudo mv osv-scanner_linux_amd64 /usr/local/bin/osv-scanner

      - name: Run OSV Scanner
        run: |
          osv-scanner scan --help
          osv-scanner scan image alpine:3.17.0 --all-packages --format spdx-2-3 --output sbom.spdx.json || true

#      - name: Run OSV Scanner
#        uses: docker://ghcr.io/google/osv-scanner-action:v2.2.1
#        with:
#          args: scan image --archive alpine_3.17.0.tar --format spdx-2-3 --all-packages > osv-scanner.spdx.json || true
#          args: scan image --archive alpine_3.17.0.tar --format json

      - name: Upload SBOM as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: osv-scanner-sbom-report
          path: sbom.spdx.json
          retention-days: 20
