name: Generate SBOM with Vuls and load into ScanCode.io

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  IMAGE_REFERENCE: "alpine:3.17"

jobs:
  generate-and-load-sbom:
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare Vuls config.toml
        run: |
          cat > config.toml <<'EOF'
          [servers]

          [servers.localhost]
          host = "localhost"
          port = "local"
          EOF

      - name: Check config
        run: |
          docker run --rm \
            -v $PWD:/workdir \
            vuls/vuls configtest \
            -config=/workdir/config.toml

      - name: Run Vuls scan
        run: |
          docker run --rm \
            -v $PWD:/workdir \
            vuls/vuls scan \
            -config=/workdir/config.toml

      - name: Run Vuls report
        run: |
          docker run --rm \
            -v $PWD:/workdir \
            vuls/vuls report \
            -config=/workdir/config.toml \
            -format-cyclonedx-json
