name: Scan Dependencies with ScanCode.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ScanCode.io
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install scancode-toolkit
          sudo pip3 install scancodeio

      - name: Scan dependencies
        run: |
          scancode --processes 2 -clp -f spdx -o results.json $GITHUB_WORKSPACE

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: results.json
